lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Site Settings
locale: "en-US"

author:
  name: "Davide Mendolia"
  bio: "Software Engineer, Ex-CEO/CTO of Karumi, Dad."
  github: "davideme"
  linkedin: "dmendolia"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
